### ISSUE TITLE
Settings.ini File Location

### ISSUE THREAD

**Issue by wilraz** [mh4x0f/extra-captiveflask#2]
Where should the "settings.ini" file be placed in the file structure?

This is not outlined in your README, nor is it discussed other than the fact that it needs to be altered...

**Comment by mh4x0f** [comment]
I forgot to insert this information on readme. please checkout I `ll edit coming soon.
look  -> /core/config/app/captive-portal.ini
``` ini 
[plugins]
FlaskDemo=true
Login_v4=false
loginPage=false
DarkLogin=false

[set_FlaskDemo]
Default=true
En=false
ptBr=false
```
the settings.ini only need to edit when you want to send me a pull request, if you do somes test, you want to  edit this file above. have fun !
